### ISSUE TITLE
Add Actor

### ISSUE THREAD

**Issue by SpurNut** [bb30/learn-duel#9]
Look into the source code and implement an actor if there is a good reason for it. If there is no reason create a dummy actor for presentation.

**Comment by SpurNut** [comment]
Possible use: Handle game instances (yet to be implemented!) of learn-duel on the server with actors.

**Comment by DonatJR** [comment]
@SailReal @SpurNut 
the implementation of the actor (Controller) which is messaged by our rest api is done: https://github.com/bb30/learn-duel/tree/9-akka-actor

I'd appreciate it if you could have a quick look at the code and tell me if there are any obvious errors or things we should discuss. There is currenctly one game instance / controller for each client (IP) generated.

I'm not yet sure how to do the gatling tests yet, as they would all come from the same IP. One way (which has to be implemented) would be to generate an ID on the "new game" rest call and allow all other rest calls only with this ID to identify the game instance. Is this something we would want in general / just for the tests / not at all...? What do you think?

**Comment by SailReal** [comment]
Looked with @SpurNut over the implementation: Pretty great work 👍

> I'd appreciate it if you could have a quick look at the code and tell me if there are any obvious errors or things we should discuss.

Maybe we should outsource the names of the function in a later step into const strings (or something better) e.g. ["onHelp"](https://github.com/bb30/learn-duel/commit/bbbca53306f2f861793c97b27b632e5653df2ba8#diff-3b14516f710e496e1ddb5541b232f965R56)

But the rest looks pretty clear and straight forward 👍 

> Is this something we would want in general / just for the tests / not at all...? What do you think?

In a later step we will support multiple games on one server so we need some mapping of users to game instances and using an ID looks pretty good. 
The main question is do we have the time to implement this in the next days?

**Comment by DonatJR** [comment]
can this be closed?

**Comment by SailReal** [comment]
👍
